# Basic Netlify configuration file

[build]
  # This command is run to build your site. 
  # Using "npm run dev" is common for some frameworks, but often "npm run build" is standard.
  # Ensure your package.json has a "dev" script.
  command = "npm run dev"

  # The directory that contains the deploy-ready HTML files and assets.
  # This is the directory that Netlify will deploy. 
  # Common examples are "dist", "build", "public", or "out".
  # You might need to change this depending on what your "npm run dev" command outputs.
  publish = "dist" 

[dev]
  # This block is for local development using the Netlify CLI (optional)
  # It tells the local dev server which command to run.
  command = "npm run dev"
